name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: paxxium.com
        username: gravitaskillis
        port: 22
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/projects/paxxserv
          git pull
          sudo /bin/systemctl restart paxxserv.service