name: Deploy to Server 
on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install cloudflared
      run: |
        curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared.deb 
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "Host ssh.paxxium.com" > ~/.ssh/config
        echo "  ProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h" >> ~/.ssh/config
        chmod 600 ~/.ssh/config
        ssh-keyscan ssh.paxxium.com >> ~/.ssh/known_hosts 
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ssh.paxxium.com
        username: gravitaskillis
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/projects/paxxserv 
          # Store the old requirements.txt hash
          OLD_HASH=$(md5sum requirements.txt 2>/dev/null | awk '{ print $1 }') 
          git pull 
          # Check if requirements.txt has changed
          NEW_HASH=$(md5sum requirements.txt | awk '{ print $1 }') 
          if [ "$OLD_HASH" != "$NEW_HASH" ]; then
            echo "requirements.txt has changed. Rebuilding virtual environment." 
            # Remove existing venv if it exists
            rm -rf venv 
            # Create a new virtual environment
            python3 -m venv venv 
            # Activate the virtual environment
            source venv/bin/activate 
            # Upgrade pip
            pip install --upgrade pip 
            # Install packages from requirements.txt
            pip install -r requirements.txt 
            # Deactivate the virtual environment
            deactivate 
            echo "Virtual environment rebuilt with updated packages."
          else
            echo "No changes in requirements.txt. Skipping package updates."
          fi 
          # Restart the service
          sudo /bin/systemctl restart paxxserv.service