name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: abyssus
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/projects/paxxserv
          git pull
          sudo systemctl restart paxxserv.service